int a = 22;
int b = 3;
int c = 9;
int max = a;
int min = a;
if (a > max) max = a;
if (b > max) max = b;
if (c > max) max = c;
Console.Write ("max = ");
Console.WriteLine (max);
if (a < min) min = a;
if (b < min) min = b;
if (c < min) min = c;
Console.Write ("min = ");
Console.WriteLine (min);